server:
  port: 8080  # 게이트웨이 포트

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: ${JWT_SECRET}
  whitelist: "/api/v1/sse/gps,/api/v1/auth/login,/api/v1/auth/join,/api/v1/auth/password-reset,/api/v1/vehicles/collector/on,/api/v1/vehicles/collector/off,/api/v1/vehicles/collector/cycle"

logging:
  level:
    root: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
