spring:
  cloud:
    gateway:
      routes:
        - id: collector
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/vehicles/collector/**

        - id: admin
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**, /api/v1/companies/**, /api/v1/customers/**, /api/v1/vehicles/**, /api/v1/rentals/**, /api/v1/logs/**, /api/v1/tracking/**

  reactor:
    context-propagation: AUTO

cors:
  allowed-origins: http://localhost:5173, http://localhost:3000
